package com.vinberts.videoconverter.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.vinberts.videoconverter.gui.actions.SetPathPreferenceAction;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 *
 */
public class VideoConverterPreferences extends JFrame {
    private JPanel mainPanel;
    private JLabel ffmpegPathLabel;
    private JLabel ffmpegPathValueLabel;
    private JButton setFFMPEGPathButton;
    private JLabel pathToConvertedLabel;
    private JLabel pathToConvertedValueLabel;
    private JButton setPathToConvertedButton;
    private JButton applyButton;

    public VideoConverterPreferences(final String title) throws HeadlessException {
        super(title);
        $$$setupUI$$$();

        setFFMPEGPathButton.setToolTipText("Change the directory to the FFMPEG installation binary");
        setFFMPEGPathButton.addActionListener(new SetPathPreferenceAction(ffmpegPathValueLabel));

        setPathToConvertedButton.setToolTipText("Change the directory that converted videos get stored in.");
        setPathToConvertedButton.addActionListener(new SetPathPreferenceAction(pathToConvertedValueLabel));

        applyButton.addActionListener((event) -> this.setVisible(false));

        this.setContentPane(mainPanel);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.pack();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        mainPanel.setMinimumSize(new Dimension(600, 65));
        ffmpegPathLabel = new JLabel();
        ffmpegPathLabel.setText("Path to FFMPEG installation:");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(ffmpegPathLabel, new CellConstraints(1, 1, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 2, 0, 0)));
        ffmpegPathValueLabel.setFocusable(true);
        ffmpegPathValueLabel.setForeground(new Color(-12961222));
        mainPanel.add(ffmpegPathValueLabel, cc.xy(3, 1));
        setFFMPEGPathButton = new JButton();
        setFFMPEGPathButton.setText("Set FFMPEG Path...");
        mainPanel.add(setFFMPEGPathButton, cc.xy(5, 1));
        pathToConvertedLabel = new JLabel();
        pathToConvertedLabel.setPreferredSize(new Dimension(198, 17));
        pathToConvertedLabel.setText("Path to store converted videos:");
        mainPanel.add(pathToConvertedLabel, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(0, 2, 0, 0)));
        pathToConvertedValueLabel.setAutoscrolls(true);
        pathToConvertedValueLabel.setBackground(new Color(-328193));
        pathToConvertedValueLabel.setForeground(new Color(-12961222));
        pathToConvertedValueLabel.setOpaque(false);
        mainPanel.add(pathToConvertedValueLabel, cc.xy(3, 3));
        setPathToConvertedButton = new JButton();
        setPathToConvertedButton.setText("Set Converted Folder...");
        mainPanel.add(setPathToConvertedButton, cc.xy(5, 3));
        applyButton.setMargin(new Insets(0, 0, 0, 0));
        applyButton.setText("Close");
        applyButton.setVerticalAlignment(0);
        applyButton.setVerticalTextPosition(0);
        mainPanel.add(applyButton, new CellConstraints(5, 5, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(5, 0, 0, 0)));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        ffmpegPathValueLabel = new JLabel();
        pathToConvertedValueLabel = new JLabel();
        applyButton = new JButton();
        String encodedPath = System.getProperty("ENCODER_PATH");
        if (Objects.isNull(encodedPath)) {
            encodedPath = "Not Defined";
        }
        pathToConvertedValueLabel.setText(encodedPath);
        String ffmpegPath = System.getProperty("FFMPEG_PATH");
        if (Objects.isNull(ffmpegPath)) {
            ffmpegPath = "Not Defined";
        }
        ffmpegPathValueLabel.setText(ffmpegPath);
    }
}
